; ProyectoMemoria - configuración generada manualmente (v0.0.1).
; Unreal completará valores adicionales (ProjectID, mapas por defecto, etc.)
; al abrir el proyecto por primera vez en el editor.

[/Script/Engine.Engine]
GameUserSettingsClassName=/Script/ProyectoMemoria.PMGameUserSettings

[/Script/EngineSettings.GameMapsSettings]
EditorStartupMap=/Game/Maps/L_Campus_Natural
GameDefaultMap=/Game/Maps/L_Campus_Natural
GlobalDefaultGameMode=/Game/Blueprints/Levels/BP_GameMode_DeveloperTesting.BP_GameMode_DeveloperTesting_C

[/Script/EnhancedInput.EnhancedInputDeveloperSettings]
bEnableUserSettings=True
InputSettingsSaveSlotName=ProyectoMemoriaInputSettings

[/Script/AndroidFileServerEditor.AndroidFileServerRuntimeSettings]
bEnablePlugin=True
bAllowNetworkConnection=True
SecurityToken=3708A16B45F625398256C48A200BF625
bIncludeInShipping=False
bAllowExternalStartInShipping=False
bCompileAFSProject=False
bUseCompression=False
bLogFiles=False
bReportStats=False
ConnectionType=USBOnly
bUseManualIPAddress=False
ManualIPAddress=

